version: "3.8"

services:
  app:
    image: sch-notification-be:latest
    container_name: sch-notification-be
    ports:
      - "7000:7000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
    network_mode: "host" # 로컬 DB 접근을 위해 host 네트워크 사용
